### ISSUE TITLE
Add VGG19

### ISSUE THREAD

**Issue by lsmale** [nnUyi/SRGAN#4]
I am wondering which vgg19 model you are using? It would be very pleasure if giving a link.

**Comment by nnUyi** [comment]
https://github.com/Sarasra/models/tree/master/research/slim>>>> you can download pre-trained model here.

**Comment by nnUyi** [comment]
You can download the pre-trained vgg19 model from here >>>>https://github.com/Sarasra/models/tree/master/research/slim. Anyway, you should add the vgg19 supported part to make sure that you program can use vgg19 model successfully.

At 2018-03-13 11:10:24, "Lsmale" <notifications@github.com> wrote:


I am wondering which vgg19 model you are using? It would be very pleasure if giving a link.

**Comment by lsmale** [comment]
Thank you very much! And I trained the model yesterday, but I got the d_loss approaching 0, is there any way to solve this?
